{{- template "auth0-operator.selfsignedcerts" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth0-operator.fullname" . }}-tls
  labels:
    {{- include "auth0-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "auth0-operator.annotations" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt:  {{ .Values._.selfsignedcerts.cacrt  | quote }}
  tls.crt: {{ .Values._.selfsignedcerts.tlscrt | quote }}
  tls.key: {{ .Values._.selfsignedcerts.tlskey | quote }}
