{{- template "auth0-operator.gen-webhook-cert" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth0-operator.fullname" . }}-tls
  labels:
    {{- include "auth0-operator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values._.CACert | quote }}
  tls.crt: {{ .Values._.WebhookCert | quote }}
  tls.key: {{ .Values._.WebhookKey | quote }}
