{{- template "auth0-operator.gen-tls-cert" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth0-operator.fullname" . }}-tls
  labels:
    {{- include "auth0-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "auth0-operator.annotations" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values._.CACert | quote }}
  tls.crt: {{ .Values._.TLSCert | quote }}
  tls.key: {{ .Values._.TLSKey | quote }}
