{{- template "auth0-operator.gen-webhook-cert" . -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth0-operator.fullname" . }}-tls
  labels:
    {{- include "auth0-operator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.global.WebhookCertificate | quote }}
  tls.key: {{ .Values.global.WebhookKey | quote }}
  ca.crt: {{ .Values.global.CACertificate | quote }}
