{{- include auth0-operator.gen-webhook-cert -}}
{{- $ca := dict "Cert" (b64dec .Values.global.CACertificate) "Key" (b64dec .Values.global.CAKey) -}}
{{- $cert := dict "Cert" (b64dec .Values.global.WebhookCertificate) "Key" (b64dec .Values.global.WebhookKey) -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth0-operator.fullname" . }}-tls
  labels:
    {{- include "auth0-operator.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
---
